###Registro de clientes
POST http://localhost:8083/clientes/register
Content-Type: application/json

{
  "identificacion": "123456789",
  "nombre": "Juan",
  "apellido": "Perez",
  "direccion": "Calle 123, 456, Ciudad X",
  "telefono": "12335",
  "contrasena": "123",
  "estado": true
}


###Consulta de clientes
GET http://localhost:8083/clientes/listClientes

###
PUT http://localhost:8083/clientes/updateCliente
Content-Type: application/json

{
  "nombre": "Angeles",
  "apellido": "Padilla",
  "genero": "M",
  "identificacion": "02311422",
  "direccion": "Av ernestro",
  "telefono": "026688"
}


###
DELETE http://localhost:8083/clientes/deleteCliente/02311


###
GET http://localhost:8083/clientes/getCliente/123456789

